### ISSUE TITLE
ConcurrentModificationException when doing external file system operations while running a ResourceTreeView

### ISSUE THREAD

**Issue by Adrodoc55** [eclipse/efxclipse-rt#29]
System details:
e(fx)clipse version: 2.5.0
OS: Windows 10
Jdk: (x64) 8_111
Jre: (x64) 8_45

I have a [small application](https://github.com/Adrodoc55/MPL/tree/idea/java-fx/ide/src/main/java/de/adrodoc55/minecraft/mpl/ide/fx) that uses a org.eclipse.fx.ui.controls.filesystem.ResourceTreeView.
When i create or move a bunch of files using the windows explorer that are displayed in the ResourceTreeView i often get a ConcurrentModificationException:
```
Exception in thread "pool-2-thread-6" java.util.ConcurrentModificationException
	at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:386)
	at java.util.AbstractList$Itr.next(AbstractList.java:355)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.eclipse.fx.ui.controls.filesystem.skin.PathItemImpl$DirPathItemImpl.handlePathModification(PathItemImpl.java:195)
	at org.eclipse.fx.ui.controls.filesystem.skin.PathItemImpl$DirPathItemImpl$$Lambda$256/681963445.accept(Unknown Source)
	at org.eclipse.fx.core.internal.FileSystemServiceImpl$CheckThread.lambda$1(FileSystemServiceImpl.java:151)
	at org.eclipse.fx.core.internal.FileSystemServiceImpl$CheckThread$$Lambda$386/1663517165.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Or this ConcurrentModificationException:
```
Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
	at java.util.SubList.checkForComodification(AbstractList.java:769)
	at java.util.SubList.listIterator(AbstractList.java:695)
	at java.util.AbstractList.listIterator(AbstractList.java:299)
	at java.util.SubList.iterator(AbstractList.java:691)
	at javafx.collections.ModifiableObservableListBase$SubObservableList.iterator(ModifiableObservableListBase.java:268)
	at java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1821)
	at java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:511)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.eclipse.fx.ui.controls.filesystem.skin.ResourceTreeViewSkin$DirTreeItem._handleListModification(ResourceTreeViewSkin.java:185)
	at org.eclipse.fx.ui.controls.filesystem.skin.ResourceTreeViewSkin$DirTreeItem.lambda$0(ResourceTreeViewSkin.java:166)
	at org.eclipse.fx.ui.controls.filesystem.skin.ResourceTreeViewSkin$DirTreeItem$$Lambda$365/973491168.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$48/349422632.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/237061348.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
	at com.sun.glass.ui.win.WinApplication$$Lambda$36/2117255219.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```
Sometimes there is also an UnsupportedOperationException:
```
Exception in thread "pool-2-thread-4" java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.add(Collections.java:1055)
	at javafx.collections.ListChangeBuilder.nextRemove(ListChangeBuilder.java:204)
	at javafx.collections.ObservableListBase.nextRemove(ObservableListBase.java:150)
	at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:181)
	at java.util.AbstractList$Itr.remove(AbstractList.java:374)
	at java.util.Collection.removeIf(Collection.java:415)
	at org.eclipse.fx.ui.controls.filesystem.skin.PathItemImpl$DirPathItemImpl.handlePathModification(PathItemImpl.java:191)
	at org.eclipse.fx.ui.controls.filesystem.skin.PathItemImpl$DirPathItemImpl$$Lambda$256/894210976.accept(Unknown Source)
	at org.eclipse.fx.core.internal.FileSystemServiceImpl$CheckThread.lambda$1(FileSystemServiceImpl.java:151)
	at org.eclipse.fx.core.internal.FileSystemServiceImpl$CheckThread$$Lambda$361/1225018599.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
I think I even saw a NullPointerException once, but i can't find the Stacktrace for that one.

**Comment by tomsontom** [comment]
I guess the problem is that we are modifying the the tree outside the UI-Thread so we need to sync back

**Comment by tomsontom** [comment]
Ups we do sync on the UI-Thread

**Comment by tomsontom** [comment]
Exception 1: Here we clearly miss a thread sync
Exception 2: I have no idea why "change.getAddedSubList()" might change
Exception 3: I guess this happens because of multi-thread access as ListChangeBuilder at some point finalizes the list of removed items

**Comment by tomsontom** [comment]
@Adrodoc55 - any news on that otherwise I'll close it

**Comment by Adrodoc55** [comment]
Well at the current state this component is basically unuseabel, because as soon as you move some files in an opened directory the component will crash. After such an exception it does not function properly anymore (does not sync with the filesystem and open events don't seem to work).
Is there a way to disable the automatic file sync? That way it would at least not break.
Regardless this definitely needs a fix!

**Comment by Adrodoc55** [comment]
I can no longer reproduce this in 3.0.0 so i guess I'll close this issue.
